# Generated by Django 3.2.5 on 2021-07-29 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=50)),
                ('region_lat', models.FloatField()),
                ('region_lon', models.FloatField()),
            ],
        ),
    ]
